using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using LicitAR.Core.Data.Models;
using LicitAR.Core.Business.Identidad;
using LicitAR.Core.Data.Models.Identidad;
using LicitAR.Web.Business.Identidad.Usuario;
using LicitAR.Web.Helpers;
using LicitAR.Web.Helpers.Authorization;
using LicitAR.Web.Models.Usuario;
using System.Text;
using Microsoft.AspNetCore.WebUtilities;

namespace LicitAR.Web.Controllers;

public class UsuarioController : Controller
{
    private readonly ILogger<UsuarioController> _logger;
    private readonly IRegistroManager _registroManager;
    private readonly SignInManager<LicitArUser> _signInManager;
    private readonly IUsuarioManager _usuarioManager;
    private readonly IRolManager _rolManager;

    public UsuarioController(SignInManager<LicitArUser> signInManager, IRegistroManager registroManager,
    ILogger<UsuarioController> logger, IUsuarioManager usuarioManager, IRolManager rolManager)
    {
        _logger = logger;
        _registroManager = registroManager;
        _signInManager = signInManager;
        _usuarioManager = usuarioManager;
        _rolManager = rolManager;
    }

    [Authorize]
    [AuthorizeClaim("Usuarios.Ver")] 
    public async Task<IActionResult> Index(string? nombre, string? apellido, string? email, string? cuit, bool? habilitado, int page = 1, int pageSize = 10)
    {
        var users = await _usuarioManager.GetAllUsersAsync();

        if (!string.IsNullOrEmpty(nombre))
        {
            users = users.Where(u => u.Nombre.Contains(nombre, StringComparison.OrdinalIgnoreCase)).ToList();
        }
        if (!string.IsNullOrEmpty(apellido))
        {
            users = users.Where(u => u.Apellido.Contains(apellido, StringComparison.OrdinalIgnoreCase)).ToList();
        }
        if (!string.IsNullOrEmpty(email))
        {
            users = users.Where(u => u.Email.Contains(email, StringComparison.OrdinalIgnoreCase)).ToList();
        }
        if (!string.IsNullOrEmpty(cuit))
        {
            cuit = new string(cuit.Where(char.IsDigit).ToArray()); // Remove non-numeric characters
            if (cuit.Length <= 11)
            {
                users = users.Where(u => u.Cuit.Contains(cuit)).ToList();
            }
        }
        if (habilitado.HasValue)
        {
            users = users.Where(u => u.Enabled == habilitado.Value).ToList();
        }

        // Order users by Apellido
        users = users.OrderBy(u => u.Apellido).ToList();

        var totalUsers = users.ToList().Count;
        var paginatedUsers = users.Skip((page - 1) * pageSize).Take(pageSize).ToList();

        ViewBag.CurrentPage = page;
        ViewBag.TotalPages = (int)Math.Ceiling(totalUsers / (double)pageSize);

        return View(paginatedUsers);
    }

    [Authorize]
    [AuthorizeClaim("Roles.Ver")]
    public async Task<IActionResult> Roles(string? nombre)
    {
        var roles = await _rolManager.GetAllRolesAsync();

        if (!string.IsNullOrEmpty(nombre))
        {
            roles = roles.Where(r => r.Name.Contains(nombre, StringComparison.OrdinalIgnoreCase)).ToList();
        }

        return View(roles);
    }

    [AllowAnonymous]
    public IActionResult Login()
    {
        return View();
    }

    [AllowAnonymous]
    public IActionResult NoAutorizado()
    {
        return View();
    }

    [AllowAnonymous]
    [HttpPost]
    public async Task<IActionResult> Login(string email, string password)
    {
        var result = await _signInManager.PasswordSignInAsync(email, password, false, false);
        if (result.Succeeded)
        {
            var user = await _usuarioManager.GetUserByEmailAsync(email);
            if (user != null)
            {
                // Use the claims generated by CustomClaimsPrincipalFactory
                var principal = await _signInManager.CreateUserPrincipalAsync(user);
                await HttpContext.SignInAsync(IdentityConstants.ApplicationScheme, principal);

                Console.WriteLine("User signed in successfully.");
                return RedirectToAction("Index", "Home");
            }
        }

        ModelState.AddModelError("", "Login incorrecto");
        return View();
    }

    [AllowAnonymous]
    public IActionResult Register()
    {
        TempData["MensajeCarga"] = "Procesando... Por favor espere.";
        return View();
    }

    [AllowAnonymous]
    [HttpPost]
    public async Task<IActionResult> Register(RegistroModel usuario)
    {
        try
        {
            if (ModelState.IsValid)
            {
                LicitArUser user = await _registroManager.RegistrarAsync(usuario, 1);
                if (user != null)
                {
                    return RedirectToAction("RegisterOk", "Usuario");

                }
            }

            ModelState.AddModelError("", "Error en el registro");
        }catch(Exception ex)
        {
            ModelState.AddModelError("", ex.Message);
        }
        return View(usuario);
    }

    [AllowAnonymous]
    public IActionResult RegisterOk()
    {
        TempData["SuccessMessage"] = "Usuario creado exitosamente!, pronto le va a llegar un correo al email registrado";
        TempData["MensajeCarga"] = "Procesando... Por favor espere.";
        return View();
    }


    [HttpGet]
    [AllowAnonymous]
    public IActionResult ConfirmarUsuario(string token, string userEmail)
    {
        TempData["Token"] = token;
        TempData["Email"] = userEmail;
        return View();
    }

    [AllowAnonymous]
    [HttpPost]
    public async Task<IActionResult> ConfirmarUsuario(string token, string email, string password)
    {
        var result = await _signInManager.PasswordSignInAsync(email, password, false, false);
        if (result.Succeeded)
        {
            string decodedToken = Encoding.UTF8.GetString(WebEncoders.Base64UrlDecode(token));

            var confirmarUsuario = await _usuarioManager.ConfirmEmailAsync(decodedToken, email);



            if (confirmarUsuario)
            {
                return RedirectToAction("Index", "Home");
            }
        }

        ModelState.AddModelError("", "Login incorrecto");
        return View();
    }



    [HttpGet]
    [AllowAnonymous]
    public IActionResult ForgotPasswordBasic()
    {
        return View();
    }

    [AllowAnonymous]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> ForgotPasswordBasic(ForgotPasswordViewModel model)
    {
        if (!ModelState.IsValid)
            return View(model);

        var user = await _usuarioManager.GetUserByEmailAsync(model.Email);
        if (user == null || !(_usuarioManager.IsEmailConfirmed(user)))
        {
            // Por seguridad, no revelamos si el usuario existe o si est� confirmado
            return RedirectToAction("ForgotPasswordConfirmation");
        }
        var result = await _registroManager.BlanquearPasswordAsync(model.Email);

        if (result != null)
        {
            TempData["SuccessMessage"] = "Se realiz� el blanqueo de la contrase�a, se envi� un link a su email";

        }


        return RedirectToAction("ForgotPasswordOk");
    }

    [HttpGet]
    [AllowAnonymous]
    public IActionResult ForgotPasswordOk()
    {
        return View();
    }

    [HttpGet]
    [AllowAnonymous]
    public IActionResult ResetPassword(string token, string email)
    {
        if (token == null || email == null)
            return BadRequest("Faltan datos");

        return View(new ResetPasswordViewModel { Password = "", ConfirmPassword = "", Token = token, Email = email });
    }

    [HttpPost]
    [AllowAnonymous]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> ResetPassword(ResetPasswordViewModel model)
    {
        if (!ModelState.IsValid)
            return View(model);

        var user = await _registroManager.ResetPasswordAsync(model.Token, model.Email, model.Password);

        if (user != null)
        {
            TempData["SuccessMessage"] = "Se realiz� el blanqueo de la contrase�a de forma exitosa, por favor click en el siguiente link para iniciar sesi�n";

            return RedirectToAction("ResetPasswordOk");
        }

        return View(model);
    }

    [HttpGet]
    [AllowAnonymous]
    public IActionResult ResetPasswordOk()
    {
        return View();
    }
    
    [AuthorizeClaim("Perfil.Ver")]
    public async Task<IActionResult> MyProfile()
    {
        if (User.Identity?.IsAuthenticated == true)
        {
            try
            {
                int idUsuario = IdentityHelper.GetUserLicitARId(User);
                var user = await _usuarioManager.GetUserAsync(idUsuario);
                if (user == null)
                {
                    return View("NotFound");
                }
                return View(user);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error in MyProfile: {ex.Message}");
                throw;
            }
        }
        else
        {
            return View("NotFound");
        }
    }

    [HttpPost]
    [Authorize]
    public IActionResult UploadPhoto()
    {
        // Placeholder logic for file upload
        return RedirectToAction("MyProfile");
    }

    [HttpPost]
    [Authorize]
    public IActionResult ResetPhoto()
    {
        // Placeholder logic for resetting photo
        return RedirectToAction("MyProfile");
    }

    [HttpPost]
    [Authorize]
    [AuthorizeClaim("Perfil.Editar")] 
    public async Task<IActionResult> EditMyProfile(UsuarioModel model)
    {
        if (!ModelState.IsValid)
        {
            _logger.LogWarning("ModelState is invalid: {@ModelState}", ModelState);
            return View("MyProfile", model);
        }

        int IdUsuario = IdentityHelper.GetUserLicitARId(User);
        _logger.LogInformation("Updating user with ID: {IdUsuario}", IdUsuario);

        try
        {
            var result = await _usuarioManager.UpdateUserAsync(model, IdUsuario);
            if (!result)
            {
                _logger.LogError("Failed to update user with ID: {IdUsuario}", IdUsuario);
                ModelState.AddModelError("", "Error al actualizar el usuario.");
                return View("MyProfile", model);
            }
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Exception occurred while updating user with ID: {IdUsuario}", IdUsuario);
            ModelState.AddModelError("", "Ocurrió un error inesperado al actualizar el perfil.");
            return View("MyProfile", model);
        }

        TempData["SuccessMessage"] = "Perfil actualizado correctamente.";
        return RedirectToAction("MyProfile");
    }

    public IActionResult GoogleLogin()
    {
        var redirectUrl = Url.Action("ExternalLoginCallback", "Account");
        var properties = _signInManager.ConfigureExternalAuthenticationProperties("Google", redirectUrl);
        return Challenge(properties, "Google");
    }

    public IActionResult MicrosoftLogin()
    {
        var redirectUrl = Url.Action("ExternalLoginCallback", "Account");
        var properties = _signInManager.ConfigureExternalAuthenticationProperties("Microsoft", redirectUrl);
        return Challenge(properties, "Microsoft");
    }

    public async Task<IActionResult> Logout()
    {
        await _signInManager.SignOutAsync();
        return RedirectToAction("Index", "Home");
    }

    [Authorize]
    [AuthorizeClaim("Usuarios.Editar")] 
    public async Task<IActionResult> Edit(int id)
    {
        var user = await _usuarioManager.GetUserAsync(id);
        if (user == null)
        {
            return View("NotFound");
        }

        return View(user);
    }

    [HttpPost]
    [AuthorizeClaim("Usuarios.Editar")]
    public async Task<IActionResult> Edit(UsuarioModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }
        int IdUsuario = IdentityHelper.GetUserLicitARId(User);
        var result = await _usuarioManager.UpdateUserAsync(model, IdUsuario);
        if (!result)
        {
            ModelState.AddModelError("", "Error al actualizar el usuario.");
            return View(model);
        }

        return RedirectToAction("Index");
    }

    [HttpPost]
    [Authorize]
    [AuthorizeClaim("Usuarios.Eliminar")] 
    public async Task<IActionResult> ToggleEnabled(int id, bool enabled)
    {
        _logger.LogInformation("ToggleEnabled called with id: {id}, enabled: {enabled}", id, enabled);

        try
        {
            var result = await _usuarioManager.ToggleUserEnabledAsync(id, enabled);
            if (!result)
            {
                _logger.LogWarning("ToggleEnabled failed for id: {id}", id);
                return View("NotFound");
            }

            _logger.LogInformation("Successfully toggled Enabled property for user ID: {id} to {enabled}", id, enabled);
            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Exception occurred while toggling Enabled property for user ID: {id}", id);
            return View("Error");
        }
    }
}
