using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using LicitAR.Core.Data.Models;
using LicitAR.Web.Business.Identidad.Usuario;
using LicitAR.Core.Business.Identidad;
using LicitAR.Web.Helpers;
using LicitAR.Web.Helpers.Authorization;

namespace LicitAR.Web.Controllers;

public class UsuarioController : Controller
{
    private readonly ILogger<UsuarioController> _logger;
    private readonly IRegistroManager _registroManager;
    private readonly SignInManager<LicitArUser> _signInManager;
    private readonly IUsuarioManager _usuarioManager;

    public UsuarioController(SignInManager<LicitArUser> signInManager, IRegistroManager registroManager,
    ILogger<UsuarioController> logger, IUsuarioManager usuarioManager)
    {
        _logger = logger;
        _registroManager = registroManager;
        _signInManager = signInManager;
        _usuarioManager = usuarioManager;
    }

    [Authorize]
    [AuthorizeClaim("Usuarios.Ver")] 
    public async Task<IActionResult> Index()
    {
        var users = await _usuarioManager.GetAllUsersAsync(); // Asegúrate de que este método devuelva datos válidos
        return View(users);
    }

    [AllowAnonymous]
    public IActionResult Login()
    {
        return View();
    }

    [AllowAnonymous]
    public IActionResult NoAutorizado()
    {
        return View();
    }

    [AllowAnonymous]
    [HttpPost]
    public async Task<IActionResult> Login(string email, string password)
    {
        var result = await _signInManager.PasswordSignInAsync(email, password, false, false);
        if (result.Succeeded)
        {
            var user = await _usuarioManager.GetUserByEmailAsync(email);
            if (user != null)
            {
                // Use the claims generated by CustomClaimsPrincipalFactory
                var principal = await _signInManager.CreateUserPrincipalAsync(user);
                await HttpContext.SignInAsync(IdentityConstants.ApplicationScheme, principal);

                Console.WriteLine("User signed in successfully.");
                return RedirectToAction("Index", "Home");
            }
        }

        ModelState.AddModelError("", "Login incorrecto");
        return View();
    }

    [AllowAnonymous]
    public IActionResult Register()
    {
        TempData["MensajeCarga"] = "Procesando... Por favor espere.";
        return View();
    }

    [AllowAnonymous]
    [HttpPost]
    public async Task<IActionResult> Register(RegistroModel usuario)
    {
        if (ModelState.IsValid) 
        {
            LicitArUser user = await _registroManager.RegistrarAsync(usuario, 1);
            if (user != null)
            {
                await _signInManager.SignInAsync(user, isPersistent: false);
                return RedirectToAction("Index", "Home");
            }
        }
        ModelState.AddModelError("", "Error en el registro");
        return View(usuario);
    }
    
    [AuthorizeClaim("Perfil.Ver")]
    public async Task<IActionResult> MiPerfil()
    {
        if (User.Identity?.IsAuthenticated == true)
        {
            // Log all claims for debugging
            var claims = User.Claims.Select(c => $"{c.Type}: {c.Value}").ToList();
            //Console.WriteLine("Available Claims in MiPerfil:");
            //claims.ForEach(Console.WriteLine);

            try
            {
                // Retrieve LicitARId from claims
                int idUsuario = IdentityHelper.GetUserLicitARId(User);
                Console.WriteLine($"Retrieved LicitARId: {idUsuario}");

                // Retrieve user by id
                var user = await _usuarioManager.GetUserAsync(idUsuario);
                if (user == null)
                {
                    Console.WriteLine($"Error: User with ID {idUsuario} not found.");
                    return NotFound();
                }

                Console.WriteLine($"User retrieved: {user.Email.ToString()}");
                return View(user);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error in MiPerfil: {ex.Message}");
                throw;
            }
        }
        else
        {
            Console.WriteLine("Error: User is not authenticated.");
            return NotFound();
        }
    }

    [HttpPost]
    [Authorize]
    [AuthorizeClaim("Perfil.Editar")] 
    public async Task<IActionResult> EditarMiPerfil(UsuarioModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }
        int IdUsuario = IdentityHelper.GetUserLicitARId(User);
        var result = await _usuarioManager.UpdateUserAsync(model, IdUsuario);
        if (!result)
        {
            ModelState.AddModelError("", "Error al actualizar el usuario.");
            return View(model);
        }
        TempData["SuccessMessage"] = "Perfil actualizado correctamente.";
        return RedirectToAction("MiPerfil");
    }

    public IActionResult GoogleLogin()
    {
        var redirectUrl = Url.Action("ExternalLoginCallback", "Account");
        var properties = _signInManager.ConfigureExternalAuthenticationProperties("Google", redirectUrl);
        return Challenge(properties, "Google");
    }

    public IActionResult MicrosoftLogin()
    {
        var redirectUrl = Url.Action("ExternalLoginCallback", "Account");
        var properties = _signInManager.ConfigureExternalAuthenticationProperties("Microsoft", redirectUrl);
        return Challenge(properties, "Microsoft");
    }

    public async Task<IActionResult> Logout()
    {
        await _signInManager.SignOutAsync();
        return RedirectToAction("Index", "Home");
    }

    [Authorize]
    [AuthorizeClaim("Usuarios.Editar")] 
    public async Task<IActionResult> Edit(int id)
    {
        var user = await _usuarioManager.GetUserAsync(id);
        if (user == null)
        {
            return NotFound();
        }

        return View(user);
    }

    [HttpPost]
    [AuthorizeClaim("Usuarios.Editar")]
    public async Task<IActionResult> Edit(UsuarioModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }
        int IdUsuario = IdentityHelper.GetUserLicitARId(User);
        var result = await _usuarioManager.UpdateUserAsync(model, IdUsuario);
        if (!result)
        {
            ModelState.AddModelError("", "Error al actualizar el usuario.");
            return View(model);
        }

        return RedirectToAction("Index");
    }

    [HttpPost]
    [Authorize]
    [AuthorizeClaim("Usuarios.Eliminar")] 
    public async Task<IActionResult> ToggleEnabled(int id, bool enabled)
    {
        var result = await _usuarioManager.ToggleUserEnabledAsync(id, enabled);
        if (!result)
        {
            return NotFound();
        }

        return RedirectToAction("Index");
    }
}
