// <auto-generated />
using System;
using LicitAR.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LicitAR.Core.Migrations.Actores
{
    [DbContext(typeof(ActoresDbContext))]
    [Migration("20250415032737_AutoMigration_Actores_20250415002646")]
    partial class AutoMigration_Actores_20250415002646
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LicitAR.Core.Data.Models.EntidadLicitante", b =>
                {
                    b.Property<int>("IdEntidadLicitante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEntidadLicitante"));

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DireccionBarrio")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DireccionCalle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DireccionCodigoPostal")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DireccionDepto")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DireccionNumero")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DireccionPiso")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("IdLocalidad")
                        .HasColumnType("int");

                    b.Property<int>("IdProvincia")
                        .HasColumnType("int");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdEntidadLicitante");

                    b.ToTable("EntidadesLicitantes");
                });

            modelBuilder.Entity("LicitAR.Core.Data.Models.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersona"));

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DireccionBarrio")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DireccionCalle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DireccionCodigoPostal")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DireccionDepto")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DireccionNumero")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DireccionPiso")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("IdLocalidad")
                        .HasColumnType("int");

                    b.Property<int>("IdProvincia")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoPersona")
                        .HasColumnType("int");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdPersona");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("LicitAR.Core.Data.Models.EntidadLicitante", b =>
                {
                    b.OwnsOne("LicitAR.Core.Data.Models.Helpers.AuditTable", "Audit", b1 =>
                        {
                            b1.Property<int>("EntidadLicitanteIdEntidadLicitante")
                                .HasColumnType("int");

                            b1.Property<DateTime>("FechaAlta")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("FechaBaja")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("FechaModificacion")
                                .HasColumnType("datetime2");

                            b1.Property<int>("IdUsuarioAlta")
                                .HasColumnType("int");

                            b1.Property<int?>("IdUsuarioBaja")
                                .HasColumnType("int");

                            b1.Property<int?>("IdUsuarioModificacion")
                                .HasColumnType("int");

                            b1.HasKey("EntidadLicitanteIdEntidadLicitante");

                            b1.ToTable("EntidadesLicitantes");

                            b1.WithOwner()
                                .HasForeignKey("EntidadLicitanteIdEntidadLicitante");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("LicitAR.Core.Data.Models.Persona", b =>
                {
                    b.OwnsOne("LicitAR.Core.Data.Models.Helpers.AuditTable", "Audit", b1 =>
                        {
                            b1.Property<int>("PersonaIdPersona")
                                .HasColumnType("int");

                            b1.Property<DateTime>("FechaAlta")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("FechaBaja")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("FechaModificacion")
                                .HasColumnType("datetime2");

                            b1.Property<int>("IdUsuarioAlta")
                                .HasColumnType("int");

                            b1.Property<int?>("IdUsuarioBaja")
                                .HasColumnType("int");

                            b1.Property<int?>("IdUsuarioModificacion")
                                .HasColumnType("int");

                            b1.HasKey("PersonaIdPersona");

                            b1.ToTable("Personas");

                            b1.WithOwner()
                                .HasForeignKey("PersonaIdPersona");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
