// <auto-generated />
using System;
using LicitAR.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LicitAR.Core.Migrations.Licitaciones
{
    [DbContext(typeof(LicitacionesDbContext))]
    [Migration("20250428001602_AutoMigration_Licitaciones_20250427211547")]
    partial class AutoMigration_Licitaciones_20250427211547
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LicitAR.Core.Data.Models.Licitacion", b =>
                {
                    b.Property<int>("IdEntidadLicitante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEntidadLicitante"));

                    b.Property<string>("CodigoLicitacion")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCategoriaLicitacion")
                        .HasColumnType("int");

                    b.Property<int>("IdEstadoLicitacion")
                        .HasColumnType("int");

                    b.Property<int>("IdLicitacion")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdEntidadLicitante");

                    b.ToTable("Licitaciones");
                });

            modelBuilder.Entity("LicitAR.Core.Data.Models.Licitacion", b =>
                {
                    b.OwnsOne("LicitAR.Core.Data.Models.Helpers.AuditTable", "Audit", b1 =>
                        {
                            b1.Property<int>("LicitacionIdEntidadLicitante")
                                .HasColumnType("int");

                            b1.Property<DateTime>("FechaAlta")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("FechaBaja")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("FechaModificacion")
                                .HasColumnType("datetime2");

                            b1.Property<int>("IdUsuarioAlta")
                                .HasColumnType("int");

                            b1.Property<int?>("IdUsuarioBaja")
                                .HasColumnType("int");

                            b1.Property<int?>("IdUsuarioModificacion")
                                .HasColumnType("int");

                            b1.HasKey("LicitacionIdEntidadLicitante");

                            b1.ToTable("Licitaciones");

                            b1.WithOwner()
                                .HasForeignKey("LicitacionIdEntidadLicitante");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
